#!/usr/bin/env python
import sys

import pseudocode



HELP = f"""
Pseudo {pseudocode.__version__}
""".strip()



if __name__ == "__main__":
    srcfile = "main.pseudo"
    if len(sys.argv) > 1:
        srcfile = sys.argv[1]
    # print(HELP)
    # print("""Usage: pseudo [FILE]""")
    # sys.exit(65)

    pseudocode.runFile(srcfile)
    